### ISSUE TITLE
weather_condition_pb2

### ISSUE THREAD

**Issue by pgmap** [sLoPPydrive/RocketMap#14]
hello,
I have this problem:

Traceback (most recent call last):
  File "./runserver.py", line 22, in <module>
    from pogom.app import Pogom
  File "/home/pgmapa/rme/RocketMap/pogom/app.py", line 13, in <module>
    from pogom.dyn_img import get_gym_icon, get_pokemon_icon
  File "/home/pgmapa/rme/RocketMap/pogom/dyn_img.py", line 7, in <module>
    from pgoapi.protos.pogoprotos.enums.weather_condition_pb2 import *
ImportError: No module named weather_condition_pb2

**Comment by rkhous** [comment]
pip install -r requirements.txt --upgrade

**Comment by sLoPPydrive** [comment]
Right. Your pgoapi isn't up-to-date.
